[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "theatrics"
version = "1.10.4"
description = "GUI for RICS, SFCS, FCS, ICS, FRAP, AFM and vesicle analysis"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
authors = [{ name = "Yusuf Qutbuddin", email = "yusuf.qutbuddin@gmail.com" }]

dependencies = [
  "numpy",
  "scipy",
  "matplotlib",
  "pandas",
  "tifffile",
  "tqdm",
  "multipletau",
  "sv-ttk",
  "pylibCZIrw",
  "scikit-image",
  "lmfit",
  "statsmodels",
  "openpyxl",
  "path",
  "AFMReader",
  "numba",
  "tttrlib",
  "pyglet",
  "platform",
]

[project.optional-dependencies]
opencv = ["opencv-python"]
cellpose = ["cellpose"]
docs = [
  "sphinx",
  "sphinx-rtd-theme",
  "myst-parser",
  "sphinx-copybutton",
]

[project.scripts]
theatrics = "theatrics.main:main"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
